### ISSUE TITLE
Are sources bootable?

### ISSUE THREAD

**Issue by remtrik** [NullCode1337/TWRP_tree_j2xlte#1]
Im tried to build twrp, but it stucks at samsung logo. Even your builds not booting..
Phone running on stock rom(G2 on end) with removed data decryption

**Comment by NullCode1337** [comment]
What phone do you have?
From the commits I'm seeing to your fork, it doesn't seem like you have a j2xlte

This tree is **only** meant for the Samsung Galaxy J2 2016 (SM-J210F) [j2xlte] or the Samsung Galaxy J2 Pro or the Samsung Galaxy J3 2016. It is **not** compatible with anything else, neither the source nor the release

**Comment by remtrik** [comment]
> From the commits I'm seeing to your fork, it doesn't seem like you have a j2xlte

Yeah this because Im porting dt for another samsung, but sadly on my j2 i cant boot your twrp. Anyway thanks for trying to help

**Comment by rxuglr** [comment]
> > From the commits I'm seeing to your fork, it doesn't seem like you have a j2xlte
Yeah this because Im porting dt for another samsung, but sadly on my j2 i cant boot your twrp. Anyway thanks for trying to help

**Comment by NullCode1337** [comment]
You can't boot TWRP on the J2 2016?
I'd be interested in that
What steps have you tried?

Also did you try flashing the official TWRP images?
